[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = 'gnn_affinity'
description = 'GNN Models for Protein-Ligand binding affinity prediction'
version = "0.1.0"
readme = 'README.md'
license = {text = "MIT"}

requires-python = ">=3.11"

dependencies = [
    "numpy==1.26.4",
    "h5py==3.16.0",
    "rdkit>=2025.9.3"
]


[project.scripts]
gnn_affinity = "main:main"

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
include = ["cli*", "train*", "models*", "datasets*", "utils*"]