MolConfig:

  Ligand:
    sanitize: false # Options: [true, false]

  Protein:
    extract_pocket: true # Options: [true, false]
    extract_method: atom # Options: [atom, cog, com]
    pocket_cutoff: 10.0
    sanitize: false # Options: [true, false]

  Formats:
    ligand: mol2

  ProteinSource: pocket # Options: [protein, pocket] // For PDBbind Dataset