MolConfig:

  Ligand:
    ligand_format: mol2 # Options: [mol2, sdf]
    sanitize: false # Options: [true, false]

  Protein:
    cutoff: 10
    method: atom # Options: [atom, cog, com]
    sanitize: false # Options: [true, false]

  ProteinSource: pocket # Options: [protein, pocket]


